import os
import snowflake.connector
from dotenv import load_dotenv

class SnowflakeLoader:
    def __init__(self):
        # Load environment variables from .env file
        load_dotenv()

    def snowflake_setup(self):
        return snowflake.connector.connect(
            user=os.getenv("SNOWFLAKE_USER"),
            password=os.getenv("SNOWFLAKE_PASSWORD"),
            account=os.getenv("SNOWFLAKE_ACCOUNT"),
            warehouse=os.getenv("SNOWFLAKE_WAREHOUSE", "WH_NEU_SA"),
            database=os.getenv("SNOWFLAKE_DATABASE", "DB_NEU_SA"),
            schema=os.getenv("SNOWFLAKE_SCHEMA", "NEU_SA"),
            role=os.getenv("SNOWFLAKE_ROLE"),
        )

    def execute_queries(self, queries):
        # Connect to Snowflake
        connection = self.snowflake_setup()
        try:
            cursor = connection.cursor()
            for query in queries:
                cursor.execute(query)
            print("Queries executed successfully!")
        except Exception as e:
            print(f"Error executing queries: {e}")
        finally:
            cursor.close()
            connection.close()

def load_program_requirements():
    """Load program requirements into the Snowflake database."""
    
    queries = [
        
        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_IS_MSIS', 'Information Systems, MSIS', 33, 3, 5, 0, 16, 12, 'CSYE 6220');""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_CPS_MS', 'Cyber-Physical Systems, MS', 33, 3, 9, 8, 0, 16, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_DAM_MS', 'Data Architecture and Management, MS', 33, 3, 17, 0, 0, 16, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_SES_MS', 'Software Engineering Systems, MS', 33, 3, 9, 0, 12, 12, 'INFO 6250');""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_TN_MS', 'Telecommunication Networks, MS', 33, 3, 13, 0, 0, 20, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_IS_MSIS_BR', 'Information Systems MSIS-Bridge', 41, 3, 13, 12, 0, 16, 'CSYE 6220');""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_IS_MSIS_BRO', 'Information Systems MSIS—Bridge—Online', 41, 3, 41, 0, 0, 0, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_IS_MSIS_O', 'Information Systems MSIS—Online', 33, 3, 33, 0, 0, 0, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_BC_SC_CERT', 'Blockchain and Smart Contract Engineering Graduate Certificate', 16, 3, 16, 0, 0, 0, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_BW_CERT', 'Broadband Wireless Systems Graduate Certificate', 16, 3, 16, 0, 0, 0, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_IPT_CERT', 'IP Telephony Systems Graduate Certificate', 16, 3, 16, 0, 0, 0, NULL);""",

        """INSERT INTO PROGRAM_REQUIREMENTS 
        (PROGRAM_ID, PROGRAM_NAME, MAX_CREDIT_HOURS, MIN_GPA, CORE_CREDIT_REQ, CORE_OPTIONS_CREDIT_REQ, SUBJECT_CREDIT_REQ, ELECTIVE_CREDIT_REQ, ELECTIVE_EXCEPTION) 
        VALUES ('MP_SES_CERT', 'Software Engineering Systems Graduate Certificate', 16, 3, 8, 8, 0, 0, NULL);""",
  
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS', 'INFO 5100');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS', 'INFO 5101');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_CPS_MS', 'TELE 6510');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_CPS_MS', 'TELE 6530');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_DAM_MS', 'DAMG 6105');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_DAM_MS', 'DAMG 6210');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_DAM_MS', 'DAMG 7250');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_DAM_MS', 'DAMG 7370');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_SES_MS', 'CSYE 6200');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_SES_MS', 'INFO 6205');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_TN_MS', 'TELE 5330');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_TN_MS', 'TELE 5331');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_TN_MS', 'TELE 5350');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_TN_MS', 'TELE 5360');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 5001');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 5002');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 5100');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 5101');""",
       
       
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 5001');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 5002');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 5100');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 5101');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'CSYE 7280');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'DAMG 6210');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 6105');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 6150');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 6245');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 6350');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BRO', 'INFO 7245');""",
		
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'INFO 5100');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'INFO 5101');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'CSYE 7280');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'DAMG 6210');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'INFO 6105');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'INFO 6150');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'INFO 6245');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'INFO 6350');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_O', 'INFO 7245');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BC_SC_CERT', 'INFO 7500');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BC_SC_CERT', 'INFO 7510');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BC_SC_CERT', 'INFO 7520');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BC_SC_CERT', 'INFO 7525');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BC_SC_CERT', 'INFO 7535');""",
		
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BW_CERT', 'TELE 5330');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BW_CERT', 'TELE 5331');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BW_CERT', 'TELE 5350');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BW_CERT', 'TELE 5360');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_BW_CERT', 'TELE 6100');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IPT_CERT', 'TELE 5330');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IPT_CERT', 'TELE 5331');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IPT_CERT', 'TELE 5350');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IPT_CERT', 'TELE 5360');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IPT_CERT', 'TELE 6350');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_SES_CERT', 'CSYE 6200');""",
        """INSERT INTO CORE_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_SES_CERT', 'INFO 6205');""",
		
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_CPS_MS', 'CSYE 6200');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_CPS_MS', 'TELE 6500');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_CPS_MS', 'TELE 6550');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'DAMG 6210');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 6150');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 6205');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 6215');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 6245');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 6255');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 6350');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 7245');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_IS_MSIS_BR', 'INFO 7385');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_SES_CERT', 'CSYE 6225');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_SES_CERT', 'CSYE 7215');""",
        """INSERT INTO CORE_OPTIONS_REQUIREMENTS (PROGRAM_ID, COURSE_CODE) VALUES ('MP_SES_CERT', 'CSYE 7280');""",
		
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_IS_MSIS', 'CSYE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_IS_MSIS', 'DAMG');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_IS_MSIS', 'INFO');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_IS_MSIS', 'TELE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_CPS_MS', 'CSYE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_CPS_MS', 'DAMG');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_CPS_MS', 'INFO');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_CPS_MS', 'TELE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_DAM_MS', 'CSYE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_DAM_MS', 'DAMG');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_DAM_MS', 'INFO');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_DAM_MS', 'TELE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_SES_MS', 'CSYE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_SES_MS', 'DAMG');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_SES_MS', 'INFO');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_SES_MS', 'TELE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_TN_MS', 'CSYE');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_TN_MS', 'DAMG');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_TN_MS', 'INFO');""",
        """INSERT INTO ELECTIVE_REQUIREMENTS (PROGRAM_ID, SUBJECT_CODE) VALUES ('MP_TN_MS', 'TELE');""",

        """INSERT INTO SUBJECT_AREAS (PROGRAM_ID, SUBJECT_CODE, MIN_CREDIT_HOURS) VALUES ('MP_SES_MS', 'CSYE', 12);""",
        """INSERT INTO SUBJECT_AREAS (PROGRAM_ID, SUBJECT_CODE, MIN_CREDIT_HOURS) VALUES ('MP_IS_MSIS', 'INFO', 16);"""
     ]

    loader = SnowflakeLoader()
    loader.execute_queries(queries)
